language: swift
osx_image: xcode11.1
xcode_workspace: Grade Converter.xcworkspace
xcode_scheme: Grade Converter
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone Xs

cache:
  directories:
    - Carthage

addons:
  homebrew:
    brewfile: true

before_install:
  - carthage bootstrap --platform ios --no-use-binaries --cache-builds

jobs:
  include:
    - stage: tests
      name: "Unit/UI Tests"
      script:
        - set -e -o pipefail
        - fastlane tests
    - stage: deploy
      name: "Deploy"
      if: (branch = master) AND (tag IS present)
      script:
        - "security set-key-partition-list -S apple-tool:,apple: -s -k ${KEYCHAIN_PASSWORD} ${KEYCHAIN_NAME}"
        - fastlane match
        - set -e -o pipefail
        - fastlane beta
