# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.49.0"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    increment_build_number
    target = options[:target] || "free"
    app_id = (target == "free") ? "com.yfujiki.gradeconverter" : "com.yfujiki.gradeconverterpro"
    scheme = (target == "free") ? "Grade Converter" : "Grade Converter Pro"
    sigh(app_identifier: app_id)
    gym(scheme: scheme)
    pilot(app_identifier: app_id)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do |options|
    # snapshot
    increment_build_number
    target = options[:target] || "free"
    app_id = (target == "free") ? "com.yfujiki.gradeconverter" : "com.yfujiki.gradeconverterpro"
    scheme = (target == "free") ? "Grade Converter" : "Grade Converter Pro"
    sigh(app_identifier: app_id)
    gym(scheme: scheme)
    deliver(force: true)
    # frameit
  end

  desc "Create archive for App Store/TestFlight"
  lane :archive do |options|
    increment_build_number
    target = options[:target] || "free"
    app_id = (target == "free") ? "com.yfujiki.gradeconverter" : "com.yfujiki.gradeconverterpro"
    scheme = (target == "free") ? "Grade Converter" : " Grade Converter Pro"
    sigh(app_identifier: app_id)
    gym(scheme: scheme)
    # You can define as many lanes as you want
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  ####### Certificates #######
  desc "Installs the certificates and profiles locally"
  lane :certificates do |options|
    if options[:use_temporary_keychain]
      create_temporary_keychain
    end

    readonly = (options[:refresh_certificates] ? false : true)
    force_for_new_devices = !readonly

    match(
      app_identifier: "com.yfujiki.gradeconverter",
      team_id: "BTWWPDZ4GE",
      type: "development",
      readonly: readonly,
      force_for_new_devices: force_for_new_devices
    )

    match(
      app_identifier: "com.yfujiki.gradeconverter",
      team_id: "BTWWPDZ4GE",
      type: "appstore",
      readonly: readonly
    )
    if options[:use_temporary_keychain]
      sh "security set-key-partition-list -S apple-tool:,apple: -s -k #{ENV["KEYCHAIN_PASSWORD"]} #{ENV["KEYCHAIN_NAME"]}"
    end
  end

  private_lane :create_temporary_keychain do
    keychain_name = "temporary_keychain"
    ENV["KEYCHAIN_NAME"] = keychain_name
    ENV["KEYCHAIN_PASSWORD"] = keychain_name

    create_keychain(
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
